[package]
name = "spooky"
version = "0.1.0"
authors = ["Juraj Mich√°lek <juraj.michalek@gmail.com>"]
edition = "2021"
license = "MIT"

[target.xtensa-esp32-none-elf.dependencies]
xtensa-atomic-emulation-trap = "0.1.0"
esp32-hal = { package = "esp32-hal", git = "https://github.com/esp-rs/esp-hal.git" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", features = [
    "esp32",
    "panic-handler",
    "print-uart",
] }
xtensa-lx-rt = { version = "0.12.0", features = ["esp32"], optional = true }
esp-println = { version = "0.2.1", features = [ "esp32" ] }

[target.xtensa-esp32s2-none-elf.dependencies]
xtensa-atomic-emulation-trap = "0.1.0"
esp32s2-hal = { package = "esp32s2-hal", git = "https://github.com/esp-rs/esp-hal.git" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", features = [
    "esp32s2",
    "panic-handler",
    "print-uart",
] }
xtensa-lx-rt = { version = "0.12.0", features = ["esp32s2"], optional = true }
esp-println = { version = "0.2.1", features = [ "esp32s2" ] }

[target.xtensa-esp32s3-none-elf.dependencies]
xtensa-atomic-emulation-trap = "0.1.0"
esp32s3-hal = { package = "esp32s3-hal", git = "https://github.com/esp-rs/esp-hal.git" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", features = [
    "esp32s3",
    "panic-handler",
    "print-uart",
] }
xtensa-lx-rt = { version = "0.12.0", features = ["esp32s3"], optional = true }
esp-println = { version = "0.2.1", features = [ "esp32s3" ] }

[target.riscv32imac-unknown-none-elf.dependencies]
esp32c3-hal = { package = "esp32c3-hal", git = "https://github.com/esp-rs/esp-hal.git" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", features = [
    "esp32c3",
    "panic-handler",
    "print-uart",
] }
riscv-rt = { version = "0.8", optional = true }
esp-println = { version = "0.2.1", features = [ "esp32c3" ] }



[dependencies]
embedded-graphics = "0.7"
embedded-hal = "0.2"
display-interface = "0.4"
display-interface-spi = "0.4"
ili9341 = { version = "0.5", git = "https://github.com/yuri91/ili9341-rs" }
st7789 = "0.6"
panic-halt = "0.2"
tinybmp = "0.3.3"


[features]
# default = [ "rt" ]
# default = [ "rt", "esp32_wrover_kit"  ]
# default = ["rt", "esp32s2_usb_otg"]
# default = ["rt", "esp32s3_usb_otg"]
# default = ["rt", "esp32s2_ili9341"]
# default = [ "rt", "esp32c3_ili9341"]
# rt = ["xtensa-lx-rt"]
# rt = ["riscv-rt"]
# eh1 = ["esp32-hal/eh1"]
# eh1 = ["esp32s2-hal/eh1"]
# eh1 = ["esp32s3-hal/eh1"]
# eh1 = ["esp32c3-hal/eh1"]

system_timer = []

esp32 = []
esp32s2 = [ "system_timer" ]
esp32s3 = [ "system_timer" ]
esp32c3 = [ "system_timer" ]

# Enable this feature in case you have an ESP32 Wrover Kit with ILI9341
esp32_wrover_kit = [ "xtensa-lx-rt", "esp32", "esp32-hal/eh1" ]

# Enable this feature in case you have an ESP32-S3-USB-OTG board with ST7789
esp32s2_usb_otg = [ "xtensa-lx-rt", "esp32s2" ]

# Enable this feature in case you have an ESP32-S3-USB-OTG board with ST7789
esp32s3_usb_otg = [ "xtensa-lx-rt", "esp32s3" ]

# Enable this feature in case you have an ESP32S2 with ILI9341
esp32s2_ili9341 = [ "xtensa-lx-rt", "esp32s2", "esp32s2-hal/eh1" ]

# Enable this feature in case you have an ESP32-C3 Rust board with ILI9341
esp32c3_ili9341 = [ "riscv-rt", "esp32c3", "esp32c3-hal/eh1" ]
